apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: team-a-ingress
  namespace: team-a-namespace
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: team-a.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: generic-app # match the Helm deployed service
            port:
              number: 80
