apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: team-a-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: team-a.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: team-a-app
            port:
              number: 80
